data_dir: /var/lib/vector
api:
  enabled: true
  address: "127.0.0.1:8686"
sources:
  docker_host:
    type: docker_logs
    include_images:
      - "supabase/postgres"
      - "supabase/gotrue"
      - "postgrest/postgrest"
      - "supabase/realtime"
      - "supabase/storage-api"
      - "kong"
transforms:
  remap_gotrue:
    type: remap
    inputs:
      - docker_host
    condition: '.container_name == "supabase-auth"'
    source: |
      .timestamp = parse_timestamp(.timestamp, "%Y-%m-%dT%H:%M:%S%.fZ") ?? now()
      .level = .level ?? "info"
  remap_postgrest:
    type: remap
    inputs:
      - docker_host
    condition: '.container_name == "supabase-rest"'
    source: |
      .timestamp = parse_timestamp(.timestamp, "%Y-%m-%dT%H:%M:%S%.fZ") ?? now()
      .level = .level ?? "info"
sinks:
  console:
    type: console
    inputs:
      - remap_gotrue
      - remap_postgrest
    encoding:
      codec: json